DROP DATABASE IF EXISTS actividadobligatoriaunidad11;
CREATE DATABASE actividadobligatoriaunidad11 CHARACTER SET utf8mb4;
USE actividadobligatoriaunidad11;

CREATE TABLE registroPersona(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NOMBRE` varchar(40) NOT NULL,
    `APELLIDO` varchar(40) NOT NULL,
    `EDAD` TINYINT UNSIGNED NOT NULL,
    `FECHA` TIMESTAMP NOT NULL,
    `PROVINCIA` varchar(40) NOT NULL
);

INSERT INTO registropersona(NOMBRE, APELLIDO, EDAD, FECHA, PROVINCIA) VALUES("FEDERICO", "GARCIA", "28", "1995-10-10", "CORDOBA");
INSERT INTO registropersona(NOMBRE, APELLIDO, EDAD, FECHA, PROVINCIA) VALUES("LYAN", "ARIAS", "33", "1993-03-05", "BUENOS AIRES");
INSERT INTO registropersona(NOMBRE, APELLIDO, EDAD, FECHA, PROVINCIA) VALUES("DEBORA", "GUTIERREZ", "30", "1999-01-20", "ROSARIO");
INSERT INTO registropersona(NOMBRE, APELLIDO, EDAD, FECHA, PROVINCIA) VALUES("MIRIAM", "GUTEMBERG", "55", "1999-10-01", "TUCUMAN");
INSERT INTO registropersona(NOMBRE, APELLIDO, EDAD, FECHA, PROVINCIA) VALUES("NIKOLA", "TESLA", "99", "1999-01-10", "MISIONES");

SELECT * FROM actividadobligatoriaunidad11.registropersona;